# Use custom format:


# format="$directory$git_branch$character"
format = """
$username\
$directory\
$cmd_duration\
$git_branch\
$character\
"""


# right_format = """$cmd_duration"""

# add_newline = true
    #icon      :  , ,󰚾 ,󱢴 ,󱍢 ,󱖲 ,󰘅 ,
    #separator :   ,   ,  , 

# [username]
# style_user = "bg:#495057 fg:#fa4e49"
# format = "[[](bold bg:none fg:#495057)󱖲 [](bg:#495057 fg:#495057)]($style)"
# disabled = false
# show_always = true

# [directory]
# style = "bg:#495057 bold fg:#eaaa00"
# format = "[[](bg:#495057 fg:#495057)$path[](bg:#none fg:#495057)]($style)"
# truncation_length = 3
# truncate_to_repo = true

# [git_branch]
# # symbol = " "
# symbol = "  " # alternate
# style = "bold bg:#eaaa00 fg:#101d22"
# format = "[[ ](bg:none fg:#eaaa00)$symbol$branch[](bg:none fg:#eaaa00 )]($style)"

# [character]
# success_symbol = "[󰜴](#b3be5a bold)"
# error_symbol = "[󰜴](#b74d50 bold)"

# [cmd_duration]
# min_time = 1
# style = "bg:#ff9e76 fg:#17161c"
# format = "[[](bold bg:none fg:#ff9e76)󱇻  $duration[](bg:#none fg:#ff9e76 )]($style)"
# disabled = false


# [username]
# style_user = "bg:#495057 fg:#fa4e49"
# format = "[[█](bold bg:none fg:#495057)󱖲 [█ ](bg:#495057 fg:#495057)]($style)"
# disabled = false
# show_always = true

[directory]
style = "fg:#BDE0FE"
# format = "[(bg:#848383 fg:#848383)$path(bg:#none fg:#848383)]($style)"
truncation_length = 3
truncate_to_repo = true

[git_branch]
# symbol = " "
symbol = "  " # alternate
style = " bg:#eaaa00 fg:#101d22"
format = "[[ ](bg:none fg:#eaaa00)$symbol$branch[ ](bg:none fg:#eaaa00 )]($style)"

[character]
success_symbol = "[](#b3be5a bold)"
error_symbol = "[](#b74d50 bold)"

[cmd_duration]
min_time = 1
style = "bg:#e9eaec fg:#17161c"
format = "[[█](bg:none fg:#e9eaec)$duration[ ](bg:#none fg:#e9eaec )]($style)"
disabled = false



# # NORDIC THEME
#
# [username]
# style_user = "bg:#69A7BA fg:#001220"
# format = "[[](bold bg:none fg:#69A7BA) [](bg:#B46950 fg:#69A7BA)]($style)"
# disabled = false
# show_always = true
#
# [directory]
# style = "bg:#B46950 fg:#001220"
# format = "[[](bg:#B46950 fg:#B46950)$path[](bg:#none fg:#B46950)]($style)"
# truncation_length = 3
# truncate_to_repo = true
#
# [git_branch]
# # symbol = " "
# symbol = "  " # alternate
# style = "bold bg:#D9B263 fg:#001220"
# format = "[[ ](bg:none fg:#D9B263)$symbol$branch[](bg:none fg:#D9B263 )]($style)"
#
# [character]
# success_symbol = "[󰜴](#A3BE8C bold)"
# error_symbol = "[󰜴](#BF616A bold)"
#
# [cmd_duration]
# min_time = 1
# style = "bg:#A89984 fg:#001220"
# format = "[[](bold bg:none fg:#A89984)󱇻  $duration[](bg:#none fg:#A89984 )]($style)"
# disabled = false

# ROSE-PINE THEME
# [username]
# style_user = "bg:#31748F fg:#001220"
# format = "[[](bold bg:none fg:#31748F) [](bg:#EBBCBA fg:#31748F)]($style)"
# disabled = false
# show_always = true
#
# [directory]
# style = "bg:#EBBCBA fg:#001220"
# format = "[[](bg:#EBBCBA fg:#EBBCBA)$path[](bg:#none fg:#EBBCBA)]($style)"
# truncation_length = 3
# truncate_to_repo = true
#
# [git_branch]
# # symbol = " "
# symbol = "  " # alternate
# style = "bold bg:#F6C177 fg:#001220"
# format = "[[ ](bg:none fg:#F6C177)$symbol$branch[](bg:none fg:#F6C177 )]($style)"
#
# [character]
# success_symbol = "[󰜴](#9CCFD8 bold)"
# error_symbol = "[󰜴](#EB6F92 bold)"
#
# [cmd_duration]
# min_time = 1
# style = "bg:#E0DEF4 fg:#001220"
# format = "[[](bold bg:none fg:#E0DEF4)󱇻  $duration[](bg:#none fg:#E0DEF4 )]($style)"
# disabled = false

# Terafox


