ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"


eval "$(starship init zsh)"
eval "$(fzf --zsh)"
eval "$(zoxide init --cmd z zsh)"
source <(fzf --zsh)

export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin:$HOME/.composer/vendor/bin:$HOME/.cargo/bin:/home/gars/node_modules:/var/lib/snapd/snap:/usr/local/go/bin/:$HOME/.local/bin:$PATH:/$HOME/go/bin:/home/linuxbrew/.linuxbrew/bin/:/home/gars/Downloads/soft/:$PATH



zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab

set -a; source ~/.env; set +a

# add some snippets
zinit snippet OMZP::git
zinit snippet OMZP::sudo
zinit snippet OMZP::command-not-found


# Auto-load completions
autoload -U compinit && compinit

zinit cdreplay -q

#History
HISTSIZE=5000
HISTFILE=~/.config/zsh/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
ZSH_CUSTOM=$HOME/.config/zsh/zshrc
QT_DIR=/usr/share/qt6


setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

#completion styling
zstyle  ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle  ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle  ':completion:*' menu no
zstyle  ':fzf-tab:complete:cd:*' fzf-preview 'ls $realpath'
zstyle  ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls $realpath' 


alias nv='nvim '
# alias i3conf     'nv $HOME/.config/i3/config '
alias picomconf='nv $HOME/.config/picom/picom.conf '
alias dunstconf='nv $HOME/.config/dunst/dunstrc '
alias kittyconf='nv $HOME/.config/kitty/kitty.conf '
alias blogdir='nv $HOME/Documents/autre/web/blog/'
alias nvimconf='nv $HOME/.config/nvim/init.lua '
alias prettier='npx prettier --write '
# alias roficonf   'nv $HOME/.config/rofi/'
alias cpySync='sh $HOME/.config/scripts/cpySync.sh '
alias termpdf='python3 $HOME/Downloads/soft/termpdf.py/termpdf.py'
alias nnn='nnn -e -a '
alias sourcef='source $HOME/.config/fish/config.fish '
alias sourcez='source $HOME/.config/zsh/zshrc'
alias fishconf='nv $HOME/.config/fish/config.fish '
alias update='sudo dnf update'
alias hyprconf='nv ~/.config/hypr/hyprland.conf'
alias ls='eza --icons '
alias planning='nv $HOME/Sync-Devices/Événements\ A\ Venir.md'
alias split_file='sh ~/.config/scripts/splitFile.sh'
alias zshconf='nv $HOME/.config/zsh/zshrc'




